org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.9

mod_version=1.0.0
maven_group=com.keoz5
archives_base_name=zombiez-companion

fabric_version=0.114.0+1.21.4

# Check latest on Modrinth: https://modrinth.com/mod/modmenu/versions
modmenu_version=13.0.0
